name: hoptimiser
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy>=1.23.5
  - pandas>=1.5.2
  - python=3.9.13
  - scipy=1.10.0
  - matplotlib=3.6.2
  - requests=2.28.1
  - psutil=5.9.0
  - pytest>=7.1.2
  - pytest-cov>=3.0.0
  - openpyxl>=3.0.10
  - pip>=22.3.1
  - pulp>=2.6.0
  - pip:
      - python-dotenv>=0.21.1
      - adal==1.2.7
      - azure-batch==12.0.0
      - azure-storage-blob==12.14.1